export const labels: Record<ResumeSections, Record<ResumeLanguages, string>> = {
  certifications: {
    portuguese: "Certificações",
    english: "Certifications",
    french: "Certifications",
    german: "Zertifizierungen",
    italian: "Certificazioni",
    spanish: "Certificaciones",
  },
  educations: {
    portuguese: "Educação",
    english: "Education",
    french: "Éducation",
    german: "Bildung",
    italian: "Istruzione",
    spanish: "Educación",
  },
  experiences: {
    portuguese: "Experiências",
    english: "Experiences",
    french: "Expériences",
    german: "Erfahrungen",
    italian: "Esperienze",
    spanish: "Experiencias",
  },
  languages: {
    portuguese: "Idiomas",
    english: "Languages",
    french: "Langues",
    german: "Sprachen",
    italian: "Lingue",
    spanish: "Idiomas",
  },
  projects: {
    portuguese: "Projetos",
    english: "Projects",
    french: "Projets",
    german: "Projekte",
    italian: "Progetti",
    spanish: "Proyectos",
  },
  skills: {
    portuguese: "Habilidades",
    english: "Skills",
    french: "Compétences",
    german: "Fähigkeiten",
    italian: "Abilità",
    spanish: "Habilidades",
  },
  socialMedias: {
    portuguese: "Redes Sociais",
    english: "Social Medias",
    french: "Réseaux Sociaux",
    german: "Soziale Medien",
    italian: "Social Media",
    spanish: "Redes Sociales",
  },
  summary: {
    portuguese: "Resumo",
    english: "Summary",
    french: "Résumé",
    german: "Zusammenfassung",
    italian: "Sommario",
    spanish: "Resumen",
  },
};